"""L4 (mocked) — browser E2E of the WP7 format-agnostic submittal-form flow
and the required-elements check.

Same harness as test_e2e_batch_ui.py (real FastAPI app on a loopback port,
headless Chromium), with BOTH extractors faked: the label extractor and the
form extractor (so the PDF/photo ingestion path runs with zero API calls).

Covers: XLSX ingestion end-to-end through openpyxl-generated bytes, the
fake-PDF path (rows preview shown, order-matching notice, scan produces a
matched worksheet), the count-mismatch block, and the per-family
required-elements flag (spirits/wine ABV -> REVIEW with the right reason;
malt ABV -> not flagged) surfacing in the worksheet, drill-down, and export.

Marked ``e2e``; skips cleanly when Playwright/Chromium is unavailable.
"""

from __future__ import annotations

import csv
import io
import socket
import threading
import time
from dataclasses import replace

import pytest

playwright_api = pytest.importorskip(
    "playwright.sync_api", reason="playwright is not installed"
)

import openpyxl
import uvicorn
from PIL import Image

from app.form_ingest import FormRow
from app.main import app, get_extractor, get_form_extractor
from app.models import ExtractedLabel
from app.rules.warning import CANONICAL_WARNING
from tests.conftest import HIGH_CONFIDENCE, FakeExtractor, FakeFormExtractor

pytestmark = pytest.mark.e2e

GOOD_EXTRACTION = ExtractedLabel(
    brand="STONE'S THROW",
    class_type="Kentucky Straight Bourbon Whiskey",
    alcohol_content="45% Alc./Vol.",
    net_contents="750 mL",
    producer="Blue Ridge Distilling Co., 12 Main Street, Asheville, NC 28801",
    origin_country=None,
    government_warning=CANONICAL_WARNING,
    warning_prefix_appears_bold=True,
    confidence=dict(HIGH_CONFIDENCE),
    label_detected=True,
)

MATCHING_FIELDS = {
    "brand": "Stone's Throw",
    "class_type": "Kentucky Straight Bourbon Whiskey",
    "abv": "45%",
    "net_contents": "750 mL",
    "producer": "Blue Ridge Distilling Co., 12 Main Street, Asheville, NC 28801",
    "origin_country": "",
    "is_import": "false",
}


def tiny_png() -> bytes:
    buffer = io.BytesIO()
    Image.new("RGB", (2, 2), "white").save(buffer, format="PNG")
    return buffer.getvalue()


PNG = tiny_png()


def memory_files(names: list[str]) -> list[dict]:
    return [{"name": name, "mimeType": "image/png", "buffer": PNG} for name in names]


def xlsx_payload(rows: list[list[object]], name: str = "submittal.xlsx") -> list[dict]:
    workbook = openpyxl.Workbook()
    for row in rows:
        workbook.active.append(row)
    buffer = io.BytesIO()
    workbook.save(buffer)
    return [{
        "name": name,
        "mimeType": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "buffer": buffer.getvalue(),
    }]


def csv_payload(text: str, name: str = "submittal.csv") -> list[dict]:
    return [{"name": name, "mimeType": "text/csv", "buffer": text.encode("utf-8")}]


def pdf_payload(name: str = "submittal.pdf") -> list[dict]:
    # Real magic bytes; the content never reaches a model — the fake answers.
    return [{"name": name, "mimeType": "application/pdf", "buffer": b"%PDF-1.4 fake form"}]


class SwitchableExtractor:
    def __init__(self) -> None:
        self.delegate = FakeExtractor(GOOD_EXTRACTION)

    def extract(self, image_bytes: bytes) -> ExtractedLabel:
        return self.delegate.extract(image_bytes)


class SwitchableFormExtractor:
    def __init__(self) -> None:
        self.delegate = FakeFormExtractor()

    def extract_rows(self, raw: bytes, kind: str) -> list:
        return self.delegate.extract_rows(raw, kind)


@pytest.fixture(scope="module")
def extractor() -> SwitchableExtractor:
    return SwitchableExtractor()


@pytest.fixture(scope="module")
def form_extractor() -> SwitchableFormExtractor:
    return SwitchableFormExtractor()


@pytest.fixture(autouse=True)
def reset_extractors(extractor: SwitchableExtractor, form_extractor: SwitchableFormExtractor):
    extractor.delegate = FakeExtractor(GOOD_EXTRACTION)
    form_extractor.delegate = FakeFormExtractor()
    yield


@pytest.fixture(scope="module")
def base_url(extractor: SwitchableExtractor, form_extractor: SwitchableFormExtractor):
    app.dependency_overrides[get_extractor] = lambda: extractor
    app.dependency_overrides[get_form_extractor] = lambda: form_extractor
    with socket.socket() as probe:
        probe.bind(("127.0.0.1", 0))
        port = probe.getsockname()[1]
    config = uvicorn.Config(app, host="127.0.0.1", port=port, log_level="warning")
    server = uvicorn.Server(config)
    thread = threading.Thread(target=server.run, daemon=True)
    thread.start()
    deadline = time.time() + 15
    while not server.started:
        if time.time() > deadline:
            pytest.fail("uvicorn did not start within 15s")
        time.sleep(0.05)
    yield f"http://127.0.0.1:{port}"
    server.should_exit = True
    thread.join(timeout=10)
    app.dependency_overrides.clear()


@pytest.fixture(scope="module")
def page(base_url):
    try:
        manager = playwright_api.sync_playwright().start()
    except Exception as exc:  # pragma: no cover - environment-dependent
        pytest.skip(f"playwright could not start: {exc}")
    try:
        browser = manager.chromium.launch()
    except Exception as exc:  # pragma: no cover - environment-dependent
        manager.stop()
        pytest.skip(f"headless Chromium is unavailable: {exc}")
    pg = browser.new_page()
    yield pg
    browser.close()
    manager.stop()


def worksheet_rows(page):
    return page.locator("#worksheet-body > tr.worksheet-row")


def wait_for_banner(page, timeout: int = 15_000):
    playwright_api.expect(page.locator("#banner-text")).to_contain_text(
        "scanned", timeout=timeout
    )


def wait_for_ingest(page, row_word: str = "row"):
    playwright_api.expect(page.locator("#csv-status")).to_contain_text(
        "Read ", timeout=10_000
    )


def matching_row(filename: str | None, **overrides: str) -> list[str]:
    fields = dict(MATCHING_FIELDS)
    fields.update(overrides)
    return [filename or "", fields["brand"], fields["class_type"], fields["abv"],
            fields["net_contents"], fields["producer"], fields["origin_country"],
            fields["is_import"]]


XLSX_HEADER = ["filename", "brand", "class_type", "abv", "net_contents",
               "producer", "origin_country", "is_import"]


class TestXlsxEndToEnd:
    def test_xlsx_ingests_previews_and_scans_to_a_matched_worksheet(self, page, base_url):
        page.goto(base_url + "/")
        page.set_input_files("#file-input", files=memory_files(["a.png", "b.png"]))
        page.set_input_files("#csv-input", files=xlsx_payload([
            XLSX_HEADER, matching_row("a.png"), matching_row("b.png"),
        ]))
        # The status line reports the parse and the preview lets the agent
        # eyeball the rows BEFORE scanning.
        playwright_api.expect(page.locator("#csv-status")).to_contain_text(
            "Read 2 rows from “submittal.xlsx”"
        )
        preview = page.locator("#ingest-preview")
        playwright_api.expect(preview).to_be_visible()
        preview.locator("summary").click()
        playwright_api.expect(preview).to_contain_text("Stone's Throw")

        page.click("#scan-button")
        playwright_api.expect(page.locator("#banner-text")).to_have_text(
            "2 labels scanned — 2 passed", timeout=15_000
        )
        playwright_api.expect(worksheet_rows(page)).to_have_count(2)
        playwright_api.expect(worksheet_rows(page).first).to_contain_text("a.png")
        playwright_api.expect(
            worksheet_rows(page).first.locator('td[data-label="Score"]')
        ).to_have_text("6/6 fields match")


class TestPdfFormPath:
    def test_pdf_rows_without_filenames_match_by_order_with_notice(
        self, page, base_url, form_extractor
    ):
        form_extractor.delegate = FakeFormExtractor(rows=[
            FormRow(brand="Stone's Throw",
                    class_type="Kentucky Straight Bourbon Whiskey",
                    abv="45%", net_contents="750 mL",
                    producer="Blue Ridge Distilling Co., 12 Main Street, Asheville, NC 28801"),
            FormRow(brand="Stone's Throw",
                    class_type="Kentucky Straight Bourbon Whiskey",
                    abv="45%", net_contents="750 mL",
                    producer="Blue Ridge Distilling Co., 12 Main Street, Asheville, NC 28801"),
        ])
        page.goto(base_url + "/")
        page.set_input_files("#file-input", files=memory_files(["first.png", "second.png"]))
        page.set_input_files("#csv-input", files=pdf_payload())

        wait_for_ingest(page)
        playwright_api.expect(page.locator("#csv-status")).to_contain_text("submittal.pdf")
        # The no-filename warning is surfaced before scanning.
        playwright_api.expect(page.locator("#form-warnings")).to_be_visible()
        playwright_api.expect(page.locator("#form-warnings")).to_contain_text(
            "matched to photos by order"
        )
        # Preview renders the LLM-parsed rows (textContent only).
        preview = page.locator("#ingest-preview")
        playwright_api.expect(preview).to_be_visible()
        preview.locator("summary").click()
        playwright_api.expect(preview).to_contain_text("Stone's Throw")

        page.click("#scan-button")
        wait_for_banner(page)
        # Persistent notice + a genuinely matched worksheet (PASS rows, not
        # no-submittal REVIEW rows).
        notice = page.locator("#match-notice")
        playwright_api.expect(notice).to_be_visible()
        playwright_api.expect(notice).to_contain_text(
            "Matched 2 rows to 2 photos by order"
        )
        playwright_api.expect(page.locator("#banner-text")).to_have_text(
            "2 labels scanned — 2 passed"
        )
        playwright_api.expect(worksheet_rows(page).first).to_contain_text("first.png")

    def test_count_mismatch_order_matches_and_reports_leftover_rows_missing(
        self, page, base_url, form_extractor
    ):
        """Report-not-block semantics (a9a6260): 3 unnamed rows + 2 photos ->
        the first 2 rows pair by order, the leftover row is a flagged MISSING
        worksheet row, and the notice explains the pairing."""
        form_extractor.delegate = FakeFormExtractor(rows=[
            FormRow(brand="One"), FormRow(brand="Two"), FormRow(brand="Three"),
        ])
        page.goto(base_url + "/")
        page.set_input_files("#file-input", files=memory_files(["a.png", "b.png"]))
        page.set_input_files("#csv-input", files=pdf_payload())
        wait_for_ingest(page)

        page.click("#scan-button")
        wait_for_banner(page)
        notice = page.locator("#match-notice")
        playwright_api.expect(notice).to_be_visible()
        playwright_api.expect(notice).to_contain_text(
            "1 form row had no matching photo — listed as MISSING"
        )
        playwright_api.expect(page.locator("#results")).to_be_visible()
        badges = page.eval_on_selector_all(
            "#worksheet-body .status-badge", "els => els.map(e => e.textContent)"
        )
        assert badges.count("MISSING") == 1, badges

    def test_unreadable_form_shows_callout_and_selects_nothing(self, page, base_url):
        page.goto(base_url + "/")
        # Real PDF magic is required: garbage bytes named .pdf get the
        # friendly unsupported-type message from the server.
        page.set_input_files("#csv-input", files=[{
            "name": "scan.pdf", "mimeType": "application/pdf", "buffer": b"not a real pdf",
        }])
        callout = page.locator("#error-callout")
        playwright_api.expect(callout).to_be_visible()
        playwright_api.expect(page.locator("#csv-dropzone-selected")).to_be_hidden()
        assert page.evaluate("document.getElementById('csv-input').files.length") == 0


class TestRequiredElements:
    """Per-family required-elements check (TTB-cited; REVIEW severity)."""

    def scan_one(self, page, base_url, manifest_row: list[str], extraction) -> None:
        page.goto(base_url + "/")
        page.set_input_files("#file-input", files=memory_files(["label.png"]))
        header = ",".join(XLSX_HEADER)
        line = ",".join('"' + cell.replace('"', '""') + '"' for cell in manifest_row)
        page.set_input_files("#csv-input", files=csv_payload(f"{header}\n{line}\n"))
        page.click("#scan-button")
        wait_for_banner(page)

    def test_spirits_missing_abv_is_review_with_field_of_vision_reason(
        self, page, base_url, extractor, tmp_path
    ):
        # Submittal doesn't declare ABV (blank -> server verdict "na") and the
        # photo shows none: spirits require it (27 CFR 5.65), same field of
        # vision as brand and class (5.61) -> REVIEW, specially worded reason.
        extractor.delegate = FakeExtractor(replace(GOOD_EXTRACTION, alcohol_content=None))
        self.scan_one(page, base_url, matching_row("label.png", abv=""), None)

        row = worksheet_rows(page).first
        playwright_api.expect(row.locator(".status-badge")).to_have_text("REVIEW")
        playwright_api.expect(row.locator(".flag")).to_have_count(1)
        playwright_api.expect(
            row.locator('td[data-label="Alcohol content"] .mark')
        ).to_have_attribute("title", "Required element — not found in this photo")

        row.locator(".review-button").click()
        block = page.locator(".required-missing")
        playwright_api.expect(block).to_be_visible()
        playwright_api.expect(block).to_contain_text("Required on every label")
        playwright_api.expect(block).to_contain_text(
            "same field of vision as the brand and class (27 CFR 5.61)"
        )
        page.keyboard.press("Escape")

        # Export: rides the existing verdict/reason columns, no new columns.
        with page.expect_download() as download_info:
            page.click("#download-csv")
        path = tmp_path / "required.csv"
        download_info.value.save_as(path)
        rows = list(csv.reader(io.StringIO(path.read_bytes().decode("utf-8-sig"))))
        header = rows[0]
        assert rows[1][header.index("pass_fail")] == "REVIEW"
        assert rows[1][header.index("abv_verdict")] == "missing_required"
        assert "27 CFR 5.61" in rows[1][header.index("abv_reason")]
        assert header[-1] == "error"  # column contract intact

    def test_malt_missing_abv_is_not_flagged(self, page, base_url, extractor):
        # Malt beverages: alcohol content is conditional (27 CFR 7.63(a)(3)),
        # so its absence must NOT flag the row.
        extractor.delegate = FakeExtractor(replace(
            GOOD_EXTRACTION, class_type="India Pale Ale", alcohol_content=None
        ))
        self.scan_one(
            page, base_url,
            matching_row("label.png", class_type="India Pale Ale", abv=""),
            None,
        )
        row = worksheet_rows(page).first
        playwright_api.expect(row.locator(".status-badge")).to_have_text("PASS")
        playwright_api.expect(row.locator(".flag")).to_have_count(0)

    def test_wine_missing_abv_is_review_with_generic_reason(self, page, base_url, extractor):
        extractor.delegate = FakeExtractor(replace(
            GOOD_EXTRACTION, class_type="Red Wine", alcohol_content=None
        ))
        self.scan_one(
            page, base_url,
            matching_row("label.png", class_type="Red Wine", abv=""),
            None,
        )
        row = worksheet_rows(page).first
        playwright_api.expect(row.locator(".status-badge")).to_have_text("REVIEW")
        row.locator(".review-button").click()
        block = page.locator(".required-missing")
        playwright_api.expect(block).to_contain_text("Alcohol content")
        playwright_api.expect(block).to_contain_text(
            "may appear on another label or be embossed on the container"
        )
        page.keyboard.press("Escape")

    def test_missing_required_element_never_downgrades_a_real_fail(
        self, page, base_url, extractor
    ):
        # Wrong brand (FAIL) + missing net contents (required): stays FAIL.
        extractor.delegate = FakeExtractor(replace(
            GOOD_EXTRACTION, brand="Completely Different", net_contents=None
        ))
        self.scan_one(page, base_url, matching_row("label.png", net_contents=""), None)
        row = worksheet_rows(page).first
        playwright_api.expect(row.locator(".status-badge")).to_have_text("FAIL")
        row.locator(".review-button").click()
        playwright_api.expect(page.locator(".required-missing")).to_contain_text(
            "Amount in bottle"
        )
        page.keyboard.press("Escape")

    def test_no_submittal_scan_still_flags_missing_required_elements(
        self, page, base_url, extractor
    ):
        # No form at all: the required-elements check is label-intrinsic and
        # still runs off the extraction (spirits family from the extracted
        # class/type; ABV missing -> flagged in the drill-down).
        extractor.delegate = FakeExtractor(replace(GOOD_EXTRACTION, alcohol_content=None))
        page.goto(base_url + "/")
        page.set_input_files("#file-input", files=memory_files(["label.png"]))
        page.click("#scan-button")
        wait_for_banner(page)
        row = worksheet_rows(page).first
        playwright_api.expect(row.locator(".status-badge")).to_have_text("REVIEW")
        row.locator(".review-button").click()
        playwright_api.expect(page.locator(".required-missing")).to_contain_text(
            "Alcohol content"
        )
        page.keyboard.press("Escape")
